services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaptive-software
    ports:
      - "2222:22"
    volumes:
      - .:/agent
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    stdin_open: true
    tty: true
