services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adaptive-software
    ports:
      - "2222:22"
    volumes:
      - .:/agent
    env_file:
      - .env
    restart: unless-stopped
    stdin_open: true
    tty: true
